name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        run: |
          docker-compose up --exit-code-from regression

      - name: Create history directory if missing
        run: |
          mkdir -p ./.github/gh-pages/history

      - name: Copy history from gh-pages to allure-results
        run: |
          mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history/" ] && [ "$(ls -A ./.github/gh-pages/history/)" ]; then
            cp -R ./.github/gh-pages/history/* allure-results/history/ || echo "Failed to copy history files."
          else
            echo "No history files to copy."
          fi

      - name: Generate Allure report
        run: |
          docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          cp -R allure-report/history/* ./.github/gh-pages/history/ || echo "Failed to update history."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true